# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='游戏名称')),
                ('code', models.IntegerField(unique=True, verbose_name='平台码')),
                ('coef', models.PositiveIntegerField(default=0, verbose_name='价格(单位:分)')),
            ],
            options={
                'verbose_name_plural': '游戏平台',
                'verbose_name': '游戏平台',
            },
        ),
    ]
